CREATE DATABASE Sdomino
GO
USE Sdomino
GO

CREATE TABLE Orders (
Id INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Description nvarchar(500) NOT NULL
)

CREATE TABLE Receipts (
Id INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id),
TotalPrice FLOAT NOT NULL,
Description NVARCHAR (500) NOT NULL
)

